font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono NF Bold
italic_font      JetBrainsMono NF Italic
bold_italic_font JetBrainsMono NF Medium Italic

cursor_trail 1

font_size 10

window_margin_width 0
window_padding_width 5

enable_audio_bell no
include dracula.conf


