################
### MONITORS ###
################
source = ~/.config/hypr/monitor_rules.conf

# SINGLE #
#monitor=eDP-1,1366x768@59.97,0x0,1
#monitor=,preferred,auto,auto
#monitor=eDP-1,disable
#monitor=HDMI-A-1,disable
#monitor=HDMI-A-1,1920x1080,0x0,1
#monitor=HDMI-A-1,2560x1080,0x0,1

# MIRROR #
#monitor=,800x600,auto,1,mirror,eDP-1

# ############ #
# EXT x LAPTOP #
# ############ #
#
# WIDESCREEN
#monitor=eDP-1,1366x768@59.973,2560x0,1
#monitor=HDMI-A-1,2560x1080@100.00,0x0,1
#monitor=HDMI-A-1,2560x1080@60.00,0x0,1

# TV
#monitor=eDP-1,1366x768,1920x0,1
#monitor=HDMI-A-1,1920x1080,0x0,1

# PROJECTOR
#monitor=eDP-1,1366x768,1024x0,1
#monitor=HDMI-A-1,1027x768,0x0,1

# LAPTOP X EXT #
# WIDESCREEN
#monitor=eDP-1,1366x768,2560x0,1
#monitor=HDMI-A-1,2560x1080,0x0,1

# TV
#monitor=eDP-1,1366x768,1920x0,1
#monitor=HDMI-A-1,1920x1080,0x0,1

# PROJECTOR
#monitor=eDP-1,1366x768,0x0,1
#monitor=HDMI-A-1,800x600,1366x0,1
